### ISSUE TITLE
Add filters/Documentation for Molecules and Atoms

### ISSUE THREAD

**Issue by agentlewis** [raisely/cli#32]
Back in the day I found Brad Frosts Atomic Design guidelines super inspirational. Not sure if this is where you are deriving these naming convensions from.

In anycase, it would be great if these were more cleary identifiable through the dev documentation. Maybe jsut adding them as a tag? it would at least be helpful for me. I'd look at the source code, but it doesn't look like that has been open-sourced. 

![image](https://user-images.githubusercontent.com/1431991/178340384-99053cd6-515b-4df6-b76d-d045cff6f9f7.png)

**Comment by tommaitland** [comment]
Thanks @agentlewis – we do use Atomic Design across Raisely which is why these categories surface in the component reference. They're also how we organise our CSS files in our templates.

I've noted the suggestion down to search by category. We use Storybook for the components.raisely.com site, so we'll just need to figure out if it's possible with storybook (I'm not too familiar with it personally).

I'll close the issue now though as it doesn't relate to the CLI repo directly.
